# Generated by Django 4.2.16 on 2024-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_address_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tax_rate',
            field=models.SmallIntegerField(default=10),
        ),
    ]
