# Generated by Django 4.2.16 on 2024-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_image',
            field=models.ImageField(blank=True, null=True, upload_to='user-signs/'),
        ),
    ]
