# Generated by Django 5.1.1 on 2024-09-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_created_at_invoice_payment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_language',
            field=models.CharField(choices=[('fa', 'fa'), ('en', 'en')], default=('fa', 'fa'), max_length=20),
        ),
    ]
