# Generated by Django 4.2.16 on 2024-09-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_invoice_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_language',
            new_name='language',
        ),
    ]
