# Generated by Django 4.2.16 on 2024-09-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_rename_invoice_language_invoice_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('irr', 'ریال'), ('usd', '$')], default=('irr', 'ریال'), max_length=20),
        ),
    ]
